### PR TITLE
#286: upgrade to .net 8 and added edge cli plugin for future

### PR DESCRIPTION
**Pull request by navancommits**
## Description / Motivation

Upgrade to .net 8 based on request

## How Has This Been Tested?

Tested in VS 2022 by building the solution as well as running .\up.ps1

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the Contributing guide.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [x] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.

### CODE REVIEW

**Comment by navancommits** [comment]
image

**Comment by robearlam** [comment]
A couple of things to fix here before we can test this...

- Can you remove the Edge CLI Plugin as we have a separate issue for tracking that work (#217)
- Can you also update the `./.env.template` image references as they're still leveraging .NET v6 base images currently.

**Comment by navancommits** [comment]
Sure, also should the node version be changed to latest lts which is 20.* in .env.template?

**Comment by robearlam** [comment]
No, you shouldn't group different changes into a single PR where possible. 

Keeping the PR's smaller and more targetted makes them much easier to review.

**Comment by robearlam** [comment]
These changes are breaking the builds for both XMC and the MVP Head. That will need to be fixed before it can be merged in.

**Comment by navancommits** [comment]
added dotnet version to the concerned build pipeline similar to what is in nextjs build yml...

**Review by robearlam — APPROVED** [review]

**Pull request merged**
