### PR TITLE
MVP Directory Rework

### PR DESCRIPTION
**Pull request by sc-ivanlieckens**
## Description / Motivation

Introduces new reworked MVP directory leveraging API Search & MVP Profile page.

Technical changes of note:
+ Nuget dependency updates
+ Removed Foundation DataFetching
+ Foundation => Feature correction of Extension name of User feature
+ MVP API Client v4.12.1 => v4.13.1
+ Caching of Profile & Search for 300s
+ Corrected namespace of People BaseModel
+ Introduced caching to Directory & Profile
+ JS is now minified
+ Cleanup Obsolete Directory
+ Fixed 404 (again) due to updated RenderingEngine
+ Introduced nullable on People Feature

Fixes:
#358
#368

## How Has This Been Tested?

Manual UI testing

Local Machine

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [X] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.

### CODE REVIEW

**Comment by sc-ivanlieckens** [comment]
@robearlam this is a test side-by-side build to validate on Staging. If @mrtamasvarga approves the new directory I'll clean out all old stuff before we finalize this PR

**Comment by robearlam** [comment]
> @robearlam this is a test side-by-side build to validate on Staging. If @mrtamasvarga approves the new directory I'll clean out all old stuff before we finalize this PR

Sounds good, just it out of draft and tag me when you want me to review

**Comment by sc-ivanlieckens** [comment]
@robearlam we're good to go for the first version. If this is all clear I'll do a quick follow with a full cleanup removing older code and views

@mrtamasvarga let's organize a small demo since this is a big change which includes the new MVP Profile page

**Comment by sc-ivanlieckens** [comment]
@robearlam all fixes are in now. Full Item cleanup will follow later.

**Comment by robearlam** [comment]
@sc-ivanlieckens - I just went to start reviewing this, and there are a bunch of changes to files in the SUGCON sites as well? 

Is this intended, as I was expecting to see the changes isolated to the MVP Site?

**Comment by sc-ivanlieckens** [comment]
@robearlam to prevent another merge/merge accident I have rebased this branch instead. This does seem to make the review a hassle ☹️

**Comment by robearlam** [comment]
I'm on PTO for two weeks after Thurs, so would like to get this merged before then to keep you moving. But in the current state I'm gonna have to diff all of the changes for the SUGCON sites with whats in main to make sure its ok, which is going to take heaps of time and could be error prone.....

Can you create a new branch, copy in the changes for the MVP site into that branch and open a new PR from there? It should then just have them appear as a single commit with only the MVP changes?  I wouldn't normally ask, but in its current state this PR has so many things raised as changed in it, its gonna be a nightmare to get through it all?

**Comment by sc-ivanlieckens** [comment]
Ok, closing this one, I'll do some cherry picking to create a true leading branch with the desired changes.

**Pull request closed without merging**
