### PR TITLE
Collapse into mobile mode sooner because of large logo

### PR DESCRIPTION
**Pull request by thomas-desmond**
Fix issue where large SUGCON NA logo overlaps with the navigation links on smaller screen sizes. 

Example of logo overlapping

## Description / Motivation

Changed bootstrap styles to collapse the navbar for screen size below XL (1200px wide).

## How Has This Been Tested?

Tested locally

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [X] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.

### CODE REVIEW

**Comment by thomas-desmond** [comment]
My XM Cloud App on Netlify video is currently in review. I'll clean those up as soon as I know the video does not need any changes.

**Review by jst-cyr — CHANGES_REQUESTED** [review]
The issue of changing to mobile sooner is definitely working. Tested it in a lot of browser sizes, screens, and devices. Everything looked okay with the home page from that perspective. I also used dev tools to change the responsive size across a variety of widths to double-check preview against prod, and it seemed okay.

Here is what I noticed that was 'off':
1. The icon shown in the tab is the old icon. (Same in production site)
2. Menu has the wrong menu options, so cannot properly test that's fitting correctly. Also seems to display a 404 page in the menu.
3. Font face and Font sizes are different between prod and preview
4. Main banner is not contained at half-width of my monitor. CTA outside the box. This doesn't happen with the prod site. The content is different, so I don't know if this is a content issue or a CSS issue. See images provided.

**PREVIEW:**
image

**PROD:**
image

**Comment by thomas-desmond** [comment]
A lot of what you bring up for items 2,3,4 are related the disconnected workflow that we have between staging and prod. Once the site was built enough in staging it was pushed to prod and now NO content changes ever get made in staging. Everything gets done in prod environment, checked for bugs in experience editor/Pages, then publhsed to Edge. Staging is not considered at all unless it is a code change in the repo. That's disconnected workflow explains your 2, 3, and 4 points made but I wouldn't say it justifies those changes just explains them. 

But good catch on the favicon tab logo. I did make a change for that.

**Comment by jst-cyr** [comment]
Wouldn't the fonts be the same between the environments? Isn't that driven by CSS? Or is that a content issue?

**Comment by thomas-desmond** [comment]
> Wouldn't the fonts be the same between the environments? Isn't that driven by CSS? Or is that a content issue?

The staging was built with XM Cloud Components that use their own styling and fonts. Prod was redone by Martin to use the old SXA components that we created in for the past SUG sites.

**Comment by jst-cyr** [comment]
Gotcha! I'll mark the PR as approved then!

**Review by jst-cyr — APPROVED** [review]

**Pull request merged**
